# Site settings
title: Ryan Huang - Software Developer
email: rphuang@ucdavis.edu
url: https://rPhase.github.io
subtitle: "I'm Ryan."
# description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
description: "a <u>dev</u>eloper."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#ffffff'

# Footer settings
footer: Ryan Huang

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/rPhase
  - title: linkedin
    url: https://linkedin.com/in/ryan-huang-842202149
# Build settings
markdown: kramdown
permalink: pretty
